### ISSUE TITLE
Testnet link dead 

### ISSUE THREAD

**Issue by misterch0c** [ethereumclassic/classic-guide#5]
The faucet link on 
http://ethereum-classic-guide.readthedocs.io/en/latest/network/test-networks.html
seems dead (https://zerogox.com/ethereum/wei_faucet)
Is there any other?

**Comment by TheCrowbill** [comment]
Confirming that this link is still offline as is the Contact link from the zerogox.com home page. I will try to find some other appropriate faucets to replace this.
